repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: format-c
        name: format-c
        entry: ./scripts/format-c
        language: system
        files: \.(c|h)$
